### DISCUSSION TITLE
Unit tests failing because of missing mysql and mongodb database

### DISCUSSION THREAD

**Discussion by luukth-infosupport** [phax/phoss-smp#240] [General]
When I clone phoss-smp locally and run `maven package` the unit tests will fail because I didn't have a mysql and mongodb database running. After starting both of these databases with a docker-compose the unit tests succeeded. Maybe this information would be useful to put on the wiki page.

I used the following docker-compose
```yaml
version: '3.9'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smp
      MYSQL_USER: smp
      MYSQL_PASSWORD: smp
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_DATABASE: phoss-smp-test
    ports:
      - "27017:27017"
```
